// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lab8Domowe2.Models;

#nullable disable

namespace lab8Domowe2.Migrations
{
    [DbContext(typeof(DbUczelnia))]
    [Migration("20240505221059_Pierwsza")]
    partial class Pierwsza
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("lab8Domowe2.Models.Uczen", b =>
                {
                    b.Property<int>("UczenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UczenId"), 1L, 1);

                    b.Property<string>("Imię")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Imie");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("Ocena")
                        .HasColumnType("float");

                    b.Property<byte>("Wiek")
                        .HasColumnType("tinyint");

                    b.HasKey("UczenId");

                    b.ToTable("Uczniowie");
                });
#pragma warning restore 612, 618
        }
    }
}
